
DROP TABLE IF EXISTS officials;
DROP TABLE IF EXISTS resident;
DROP TABLE IF EXISTS users;


CREATE TABLE officials (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name VARCHAR(255) NOT NULL,
	chair VARCHAR(255) NOT NULL,
	position VARCHAR(255) NOT NULL,
	contact VARCHAR(255) NOT NULL
);

CREATE TABLE resident (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    citizenship VARCHAR(255) NOT NULL,
    bplace VARCHAR(255) NOT NULL,
    bdate DATE NOT NULL,
    age VARCHAR(255) NOT NULL,
    cstatus VARCHAR(255) NOT NULL,
    gender VARCHAR(255) NOT NULL,
    purok VARCHAR(255) NOT NULL,
    contact VARCHAR(255) NOT NULL,
    occupation VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL

);

CREATE TABLE users (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	fullname VARCHAR(255) NOT NULL,
	username VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL
);